# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d812350cb606340c8cf603033307e58ae346c10b34ae544b233dd5e8438d4452253d7ae937d061c6fb4e4f339f9c5c323dbb8f7d76af6df455d489f19a8f80d

test:
  secret_key_base: 1c9487b4dd42168955dd7ee2317150cdac83c78c220ad8fc570e06ff6c9101df23ce18d62af45777d8546dcfdde3701a95e0298a5c686c41b0856d2591437e45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
